############################################## USERS ##############################################

### Get all users
GET http://localhost:7005/users HTTP/1.1
X-JWT-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0ZjkwYTNhYi1kMWJhLTRhOTEtODViNy1kOTBjY2I0Y2RjNjAiLCJleHAiOjE2NDg3MjU1MTEsImlhdCI6MTY0ODYzOTExMX0.4EbnyRredA0HU-pk1_OuxjMTAgU8Q01nWGDQVUBr3IU

### Get single user
GET http://localhost:7005/users/0ab8c67b-34ab-48c9-9ade-0da5975ea8ab HTTP/1.1

### Not Found
GET http://localhost:7005/users/11111111-2222-3333-4444-555555555555 HTTP/1.1

### Update user
PUT http://localhost:7005/users/8478fc36-5bbb-410a-bc0f-20fe1e4daf3d HTTP/1.1
Content-Type: application/json

{
  "name":"WEB Userovic"
}

### Create user - password: moj-password
POST http://localhost:7005/register HTTP/1.1
Content-Type: application/json

{
  "name": "user1",
  "password": "bd9b052ffa71319279b57b0df43cfa681eb12662af4ed8003f437fac3661a3e2"
}

### Authorize user - password: moj-password
POST http://localhost:7005/authentificate HTTP/1.1
Content-Type: application/json

{
  "name": "user1",
  "password": "bd9b052ffa71319279b57b0df43cfa681eb12662af4ed8003f437fac3661a3e2"
}

############################################## TASKS ##############################################

### Create task with assignee
POST http://localhost:7005/tasks HTTP/1.1
Content-Type: application/json

{
  "name":"REST moja uloha",
  "creator": {
    "_id":"512f9786-2411-47a8-a732-a53a31ac4958",
    "name":"REST Userovic"
  },
  "description":"raz dva tri",
  "assignee":{
    "_id":"6fdc3482-bde8-4c0f-a8df-a723e197d305",
    "name":"REST Userovic druhy"
  }
}

### Get Tasks for user
GET http://localhost:7005/tasks/user/512f9786-2411-47a8-a732-a53a31ac4958 HTTP/1.1
Content-Type: application/json

### Get All Tasks
GET http://localhost:7005/tasks HTTP/1.1
Content-Type: application/json
X-JWT-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb25zb2lsaXVtX3RlbXB1cyIsInN1YiI6ImEwYjI4NzQwLWJjNjMtNGVjZC05YWVlLTMyMGFiMWQ5OTQ3OSIsImV4cCI6MTY0ODcyODk1MCwiaWF0IjoxNjQ4NjQyNTUwfQ.BoV1Pcae5VicG5OLqYrkoPmrfY88X_tsh07hB8Xd1vw

### Update state of task
PUT http://localhost:7005/tasks/86867706-191e-43a1-9e9b-ba37ed51c10b HTTP/1.1
Content-Type: application/json

{
  "status": 1
}


########################################## REFERENCE DATA #########################################

### Get all reference data
GET http://localhost:7005/reference_data HTTP/1.1





